// frontend/src/components/product/ProductCard.svelte
<script>
  import { push } from 'svelte-spa-router';
  import { cart } from '../../stores/cart';
  import ProductDetail from './ProductDetail.svelte';

  export let product;

  let isProductModalOpen = false;

  function addToCart() {
    const existingItem = $cart.find(item => item.id === product.id);
    if (existingItem) {
      cart.update(items =>
        items.map(item =>
          item.id === product.id
            ? { ...item, quantity: item.quantity + 1 }
            : item
        )
      );
    } else {
      cart.update(items => [...items, { ...product, quantity: 1 }]);
    }
  }

  function handleProductClick() {
    push(`/product/${product.id}`);
  }
</script>

<div class="bg-white dark:bg-gray-800 rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300">
  <a href="/products/{product.id}" class="block">
    <div class="relative pb-[100%]">
      <img
        src={product.image}
        alt={product.name}
        class="absolute inset-0 w-full h-full object-cover"
      />
    </div>
    <div class="p-4">
      <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-2 line-clamp-2">
        {product.name}
      </h3>
      <p class="text-sm text-gray-600 dark:text-gray-400 mb-2 line-clamp-2">
        {product.description}
      </p>
      <div class="flex justify-between items-center">
        <span class="text-lg font-bold text-gray-900 dark:text-white">
          ${product.price.toFixed(2)}
        </span>
        <button
          class="bg-black dark:bg-white text-white dark:text-black px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-800 dark:hover:bg-gray-100 transition-colors duration-300"
        >
          Add to Cart
        </button>
      </div>
    </div>
  </a>
</div>

<ProductDetail
  bind:isOpen={isProductModalOpen}
  {product}
  on:close={() => {
    isProductModalOpen = false;
  }}
/>

// src/components/products/ProductCard.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import { useCart } from "../../context/cart/context";
import { Cart4 } from "react-bootstrap-icons";
import { formatCurrency } from "../../utils/format";

export default function Product(props) {
  const { addToCart } = useCart();
  const [isAdded, setIsAdded] = useState(false);

  const handleAddToCart = () => {
    addToCart(props.product);
    setIsAdded(true);
    setTimeout(() => {
      setIsAdded(false);
    }, 3000);
  };

  return (
    <div className="bg-white shadow-sm shadow-neutral-200 ring- ring-gray-300 overflow-hidden transition-transform transform">
      <div className="relative">
        {!props.product.onsale && (
          <div className="absolute z-50 left-4 top-4 bg-red-500 text-white text-xs px-2 py-1 transition-all duration-300 hover:bg-red-400">
            Almost sold out
          </div>
        )}
        <Link to={`/product/${props.product.id}`} className="block">
          <img
            className="relative rounded lg:h-[28rem] h-72 w-full object-cover"
            src={props.product.imageUrl || props.product.image}
            alt={props.product.title}
            loading="lazy"
          />
        </Link>
      </div>
      <div className="flex flex-col">
        <div className="gap-2 justify-between flex">
          <span className="py-1 px-2 bg-white md:text-base text-black flex items-center truncate">
            {props.product.title}
          </span>
          <span className="py-1 hidden  font-bold md:text-lg px-2 bg-white text--400 md:flex items-center">
            {formatCurrency(props.product.price)}
          </span>
        </div>
        <div className="justify-between items-center flex pb-2 px-2">
        </div>
      </div>
    </div>
  );
}
