// src/pages/admin/coupon.jsx
import React, { useEffect, useState } from "react";
import { db } from "../../firebase/firebase";
import {
  doc,
  writeBatch,
  collection,
  getDocs,
  deleteDoc,
} from "firebase/firestore";
import { nanoid } from "nanoid";
import Toast from "../../components/common/toast";

const couponConfig = ["discount", "startDate", "endDate", "code"];

export default function UploadCoupon() {
  const [formData, setFormData] = useState({
    discount: 0,
    startDate: "",
    endDate: "",
    code: "",
  });
  const [uploading, setUploading] = useState(false);
  const [coupons, setCoupons] = useState([]);
  const [editingId, setEditingId] = useState(null);

  useEffect(() => {
    fetchCoupons();
  }, []);

  const fetchCoupons = async () => {
    const snapshot = await getDocs(collection(db, "coupons"));
    const loadedCoupons = snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    }));
    setCoupons(loadedCoupons);
  };

  const handleChange = (e) => {
    const { id, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [id]: value,
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!formData.code || !formData.discount) {
      Toast({ type: "error", message: "Please fill in all required fields." });
      return;
    }

    setUploading(true);
    try {
      const batch = writeBatch(db);
      const documentId = editingId || nanoid(8);
      const docRef = doc(db, "coupons", documentId);

      batch.set(docRef, {
        ...formData,
      });

      await batch.commit();
      Toast({ type: "success", message: `Coupon ${editingId ? "updated" : "added"} successfully!` });

      setFormData({ discount: 0, startDate: "", endDate: "", code: "" });
      setEditingId(null);
      fetchCoupons();
    } catch (err) {
      console.error(err);
      Toast({ type: "error", message: "Error saving coupon." });
    } finally {
      setUploading(false);
    }
  };

  const handleEdit = (coupon) => {
    setFormData(coupon);
    setEditingId(coupon.id);
  };

  const handleDelete = async (id) => {
    try {
      await deleteDoc(doc(db, "coupons", id));
      Toast({ type: "success", message: "Coupon deleted." });
      fetchCoupons();
    } catch (err) {
      console.error(err);
      Toast({ type: "error", message: "Failed to delete coupon." });
    }
  };

  return (
    <div className="w-full p-6 flex bg-secondary min-h-svh justify-center items-start">
      <div className="w-full p-6 bg-white shadow-sm max-w-4xl mx-auto rounded-sm">
        <h2 className="text-2xl my-4">{editingId ? "Edit Coupon" : "Upload Coupon"}</h2>

        <form onSubmit={handleSubmit} className="space-y-2 w-full">
          {couponConfig.map((field) => (
            <div key={field} className="flex flex-col items-start w-full">
              <label htmlFor={field} className="text-lg text-neutral-700 capitalize">
                {field}
              </label>
              <input
                type={field === "discount" ? "number" : field.includes("Date") ? "date" : "text"}
                id={field}
                value={formData[field] || ""}
                onChange={handleChange}
                className="block w-full border-gray-400 rounded-sm ring-1 ring-neutral-400 p-2 focus:outline-primary/30"
                required
              />
            </div>
          ))}

          <button
            type="submit"
            className="w-full bg-primary text-white font-medium py-2 rounded-sm shadow-sm hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary"
            disabled={uploading}
          >
            {uploading ? "Saving..." : editingId ? "Update Coupon" : "Upload Coupon"}
          </button>
        </form>

        {/* Coupon List */}
        <div className="mt-8">
          <h3 className="text-xl font-semibold mb-2">Existing Coupons</h3>
          <div className="space-y-3">
            {coupons.length === 0 && <p className="text-neutral-500">No coupons available.</p>}
            {coupons.map((coupon) => (
              <div key={coupon.id} className="p-3 border rounded-md bg-gray-50 flex justify-between items-center">
                <div>
                  <p className="font-bold">{coupon.code}</p>
                  <p>Discount: {coupon.discount}%</p>
                  <p>Valid: {coupon.startDate} → {coupon.endDate}</p>
                </div>
                <div className="space-x-2">
                  <button
                    onClick={() => handleEdit(coupon)}
                    className="text-blue-600 text-sm"
                  >
                    Edit
                  </button>
                  <button
                    onClick={() => handleDelete(coupon.id)}
                    className="text-red-500 text-sm"
                  >
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/pages/admin/Coupon.svelte
<script>
  import Button from '../../components/common/Button.svelte';
  let coupons = [
    { id: 1, code: 'WELCOME10', discount: 10, expiry: '2024-12-31' },
    { id: 2, code: 'FREESHIP', discount: 0, expiry: '2024-10-01' }
  ];
  let showModal = false;
  let newCoupon = { code: '', discount: '', expiry: '' };
  let editingId = null;
  function openAddModal() {
    editingId = null;
    newCoupon = { code: '', discount: '', expiry: '' };
    showModal = true;
  }
  function openEditModal(coupon) {
    editingId = coupon.id;
    newCoupon = { ...coupon };
    showModal = true;
  }
  function saveCoupon() {
    if (editingId) {
      coupons = coupons.map(c => c.id === editingId ? { ...newCoupon, id: editingId } : c);
    } else {
      coupons = [...coupons, { ...newCoupon, id: Date.now() }];
    }
    showModal = false;
  }
  function deleteCoupon(id) {
    if (confirm('Delete this coupon?')) {
      coupons = coupons.filter(c => c.id !== id);
    }
  }
</script>
<div class="max-w-3xl mx-auto px-2 sm:px-8 py-10">
  <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center mb-12 gap-4">
    <h1 class="text-4xl font-extrabold uppercase tracking-widest text-black dark:text-white">Coupon Management</h1>
    <Button variation="stroke" class="font-extrabold uppercase tracking-widest border-2 border-black dark:border-white text-black dark:text-white rounded-full px-8 py-3" on:click={openAddModal}>Add Coupon</Button>
  </div>
  <div class="bg-white dark:bg-black border-2 border-black dark:border-white rounded-2xl shadow-xl overflow-x-auto">
    <table class="min-w-full divide-y divide-black dark:divide-white text-sm">
      <thead class="bg-white dark:bg-black">
        <tr>
          <th class="px-6 py-4 text-left text-xs font-extrabold uppercase tracking-widest text-black dark:text-white">Code</th>
          <th class="px-6 py-4 text-left text-xs font-extrabold uppercase tracking-widest text-black dark:text-white">Discount (%)</th>
          <th class="px-6 py-4 text-left text-xs font-extrabold uppercase tracking-widest text-black dark:text-white">Expiry</th>
          <th class="px-6 py-4 text-left text-xs font-extrabold uppercase tracking-widest text-black dark:text-white">Actions</th>
        </tr>
      </thead>
      <tbody class="bg-white dark:bg-black divide-y divide-black dark:divide-white">
        {#each coupons as coupon}
          <tr>
            <td class="px-6 py-4 whitespace-nowrap text-base font-bold text-black dark:text-white">{coupon.code}</td>
            <td class="px-6 py-4 whitespace-nowrap text-base font-bold text-black dark:text-white">{coupon.discount}</td>
            <td class="px-6 py-4 whitespace-nowrap text-base text-black dark:text-white">{coupon.expiry}</td>
            <td class="px-6 py-4 whitespace-nowrap flex gap-2">
              <Button variation="stroke" class="font-extrabold uppercase tracking-widest border-2 border-black dark:border-white text-black dark:text-white rounded-full px-4 py-2" on:click={() => openEditModal(coupon)}>Edit</Button>
              <Button variation="stroke" class="font-extrabold uppercase tracking-widest border-2 border-red-500 text-red-500 rounded-full px-4 py-2" on:click={() => deleteCoupon(coupon.id)}>Delete</Button>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  {#if showModal}
    <div class="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-50">
      <div class="bg-white dark:bg-black border-2 border-black dark:border-white rounded-2xl shadow-2xl p-8 max-w-md w-full max-h-[90vh] overflow-y-auto relative">
        <h2 class="text-2xl font-extrabold uppercase tracking-widest mb-8 text-black dark:text-white text-center">{editingId ? 'Edit' : 'Add'} Coupon</h2>
        <form on:submit|preventDefault={saveCoupon} class="space-y-6">
          <div>
            <label class="block text-xs font-bold uppercase tracking-widest text-gray-700 dark:text-gray-300 mb-2">Code</label>
            <input class="w-full border-2 border-black dark:border-white rounded-lg px-4 py-2 bg-white dark:bg-black text-black dark:text-white focus:outline-none focus:ring-2 focus:ring-black dark:focus:ring-white" bind:value={newCoupon.code} required />
          </div>
          <div>
            <label class="block text-xs font-bold uppercase tracking-widest text-gray-700 dark:text-gray-300 mb-2">Discount (%)</label>
            <input type="number" class="w-full border-2 border-black dark:border-white rounded-lg px-4 py-2 bg-white dark:bg-black text-black dark:text-white focus:outline-none focus:ring-2 focus:ring-black dark:focus:ring-white" bind:value={newCoupon.discount} required />
          </div>
          <div>
            <label class="block text-xs font-bold uppercase tracking-widest text-gray-700 dark:text-gray-300 mb-2">Expiry</label>
            <input type="date" class="w-full border-2 border-black dark:border-white rounded-lg px-4 py-2 bg-white dark:bg-black text-black dark:text-white focus:outline-none focus:ring-2 focus:ring-black dark:focus:ring-white" bind:value={newCoupon.expiry} required />
          </div>
          <div class="mt-8 flex justify-end gap-4">
            <Button variation="ghost" class="font-extrabold uppercase tracking-widest border-2 border-black dark:border-white text-black dark:text-white rounded-full px-8 py-3" type="button" on:click={() => showModal = false}>Cancel</Button>
            <Button variation="stroke" class="font-extrabold uppercase tracking-widest border-2 border-black dark:border-white text-black dark:text-white rounded-full px-8 py-3" type="submit">Save</Button>
          </div>
        </form>
      </div>
    </div>
  {/if}
</div>
