// frontend/src/components/layout/Hero.svelte
<script>
  import { onMount } from 'svelte';
  import { push } from 'svelte-spa-router';
  import { products } from '../../stores/products';

  let currentIndex = 0;
  let banners = $products?.banners || [];
  let isLoading = true;

  function nextSlide() {
    currentIndex = currentIndex === banners.length - 1 ? 0 : currentIndex + 1;
  }

  function goToSlide(index) {
    currentIndex = index;
  }

  function handleNavigation(href) {
    if (!href) return;
    if (href.startsWith('http') || href.startsWith('www.')) {
      window.open(href.startsWith('www.') ? `https://${href}` : href, '_blank');
    } else {
      push(href);
    }
  }

  onMount(() => {
    const interval = setInterval(nextSlide, 10000);
    isLoading = false;
    return () => clearInterval(interval);
  });
</script>

<section class="relative h-[70vh] bg-pink-50 dark:bg-gray-800">
  {#if banners?.length > 0}
    <!-- Banner Image -->
    <div class="absolute inset-0">
      <img
        src={banners[currentIndex]?.imageUrl}
        alt={banners[currentIndex]?.title}
        class="w-full h-full object-cover opacity-50"
        loading="lazy"
      />
    </div>

    <!-- Content -->
    <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-full flex items-center">
      <div class="text-black dark:text-white">
        <h1 class="text-5xl md:text-6xl font-bold mb-6 tracking-wider">
          {banners[currentIndex]?.title || 'SUMMER COLLECTION 2024'}
        </h1>
        <p class="text-xl md:text-2xl mb-8 max-w-2xl">
          {banners[currentIndex]?.description || 'Discover the latest trends in fashion with our exclusive summer collection. Limited edition pieces that define style and comfort.'}
        </p>
        <button
          class="px-8 py-4 bg-primary-light dark:bg-primary-dark text-black dark:text-white rounded-lg hover:bg-opacity-90 transition-colors tracking-wider text-lg"
          on:click={() => handleNavigation(banners[currentIndex]?.category ? `/products/${banners[currentIndex]?.category}` : '/products')}
        >
          SHOP NOW
        </button>
      </div>
    </div>

    <!-- Dots Indicator -->
    <div class="absolute bottom-4 flex justify-center w-full space-x-2">
      {#each banners as _, index}
        <div
          class="h-2 w-2 md:h-3 md:w-3 rounded-full cursor-pointer transition-all {index === currentIndex
            ? 'bg-secondary scale-110 md:scale-125'
            : 'bg-gray-400'}"
          on:click={() => goToSlide(index)}
        ></div>
      {/each}
    </div>
  {:else}
    <!-- Fallback Hero -->
    <div class="absolute inset-0">
      <img
        src="/images/hero-bg.jpg"
        alt="Hero background"
        class="w-full h-full object-cover opacity-50"
      />
    </div>
    <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-full flex items-center">
      <div class="text-black dark:text-white">
        <h1 class="text-5xl md:text-6xl font-bold mb-6 tracking-wider">
          SUMMER COLLECTION 2024
        </h1>
        <p class="text-xl md:text-2xl mb-8 max-w-2xl">
          Discover the latest trends in fashion with our exclusive summer collection.
          Limited edition pieces that define style and comfort.
        </p>
        <button
          class="px- 8 py- 4 bg-primary-light dark:bg-primary-dark text-black dark:text-white rounded-lg hover:bg-opacity-90 transition-colors tracking-wider text-lg"
          on:click={() => push('/products')}
        >
          SHOP NOW
        </button>
      </div>
    </div>
  {/if}
</section>

// YNT-react-firebase/src/components/layout/hero.js
import React, { useState, useEffect } from "react";
// import { ChevronLeft, ChevronRight } from "react-bootstrap-icons";
import { useNavigate } from "react-router-dom";
import { useProducts } from "../../context/products/context";
import { Load } from "../skeletons/loading";

function Hero() {
  const { products = {} } = useProducts();
  const banners = products?.banners || [];
  const [currentIndex, setCurrentIndex] = useState(0);
  const navigate = useNavigate();

  const nextSlide = () =>
    setCurrentIndex((prevIndex) =>
      prevIndex === banners.length - 1 ? 0 : prevIndex + 1
    );
  // Auto-slide every 5 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      nextSlide();
    }, 10000);

    return () => clearInterval(interval); // Cleanup interval on unmount
  }, [currentIndex, nextSlide]); // Restart interval when currentIndex changes

  const handleNavigation = (href) => {
    if (!href) return;
    if (href.startsWith("http") || href.startsWith("www.")) {
      window.open(href.startsWith("www.") ? `https://${href}` : href, "_blank");
    } else {
      navigate(href);
    }
  };

  // const prevSlide = () =>
  //   setCurrentIndex((prevIndex) =>
  //     prevIndex === 0 ? banners.length - 1 : prevIndex - 1
  //   );

  const goToSlide = (index) => setCurrentIndex(index); // Jump to a specific slide

  return (
    <div className="relative flex items-center justify-center min-h-[30vh] lg:min-h-[70vh] bg-black">
      {banners?.length > 0 ? (
        <>
          <img
            src={banners[currentIndex]?.imageUrl}
            alt={banners[currentIndex]?.title}
            className="absolute inset-0 object-cover object-center w-full h-full"
            loading="lazy"
          />
          <div className="absolute inset-0 bg-black opacity-50"></div>

          {/* Text Content */}
          <div className="relative w-full md:max-w-6xl px-1 md:px-6 text-center md:py-20 space-y-4">
            <h4 className="text-secondary text-3xl md:text-6xl font-black ">
              {banners[currentIndex]?.title}
            </h4>
            <p className="text-secondary hidden md:block text-2xl font-normal">
              {banners[currentIndex]?.description ||
                banners[currentIndex]?.subtitle}
            </p>
            <button
              onClick={() => navigate(`products/${banners[currentIndex]?.category}`)}
              className="md:px-6 md:py-2 p-1 bg-secondary text-sm lg:text-xl text-black font- bold rounded-sm hover:bg-slate-100 transition"
            >
              shop
            </button>
          </div>

          {/* Dots Indicator */}
          <div className="absolute bottom-4 flex justify-center w-full space-x-2">
            {banners.map((_, index) => (
              <div
                key={index}
                className={`h-2 w-2 md:h-3 md:w-3 rounded-full cursor-pointer transition-all ${
                  index === currentIndex
                    ? "bg-secondary scale-110 md:scale-125"
                    : "bg-gray-400"
                }`}
                onClick={() => goToSlide(index)}
              ></div>
            ))}
          </div>
        </>
      ) : (
        <Load />
      )}
    </div>
  );
}

export default Hero;
